% function [Jac,Fun] = TFC_Riccati_Loss_5_Jac(xi,setup)
% 
% Jacobian wrapper file generated by ADiGator
% ©2010-2014 Matthew J. Weinstein and Anil V. Rao
% ADiGator may be obtained at https://sourceforge.net/projects/adigator/ 
% Contact: mweinstein@ufl.edu
% Bugs/suggestions may be reported to the sourceforge forums
%                    DISCLAIMER
% ADiGator is a general-purpose software distributed under the GNU General
% Public License version 3.0. While the software is distributed with the
% hope that it will be useful, both the software and generated code are
% provided 'AS IS' with NO WARRANTIES OF ANY KIND and no merchantability
% or fitness for any purpose or application.

function [Jac,Fun] = TFC_Riccati_Loss_5_Jac(xi,setup)
gator_xi.f = xi;
gator_xi.dxi = ones(225,1);
loss = TFC_Riccati_Loss_5_ADiGatorJac(gator_xi,setup);
varloc = (loss.dxi_location(:,3)-1)*15 + loss.dxi_location(:,2);
Jac = sparse(loss.dxi_location(:,1),varloc,loss.dxi,300,225);
Fun = loss.f;
end