function Hes = objfun_Hes(x,lambda)
% 
% Wrapper file generated by ADiGator
% ©2010-2014 Matthew J. Weinstein and Anil V. Rao
% ADiGator may be obtained at https://sourceforge.net/projects/adigator/ 
% Contact: mweinstein@ufl.edu
% Bugs/suggestions may be reported to the sourceforge forums
%                    DISCLAIMER
% ADiGator is a general-purpose software distributed under the GNU General
% Public License version 3.0. While the software is distributed with the
% hope that it will be useful, both the software and generated code are
% provided 'AS IS' with NO WARRANTIES OF ANY KIND and no merchantability
% or fitness for any purpose or application.

global ADiGator_confun_ADiGatorHes
gx.f = x;
gx.dx = ones(2,1);
obj = objfun_ADiGatorHes(gx);
objHes = zeros(2,2);
objHes((obj.dxdx_location(:,2)-1)*2+obj.dxdx_location(:,1)) = obj.dxdx;
[con, coneq] = confun_ADiGatorHes(gx);
HesData1 = ADiGator_confun_ADiGatorHes.confun_ADiGatorHes.Gator2Data.HesData1;
conHesnz = lambda.ineqnonlin.'*sparse(con.dxdx_location(:,1),HesData1,con.dxdx,2,2);
HesData2 = ADiGator_confun_ADiGatorHes.confun_ADiGatorHes.Gator2Data.HesData2;
conHes = sparse(HesData2(:,1),HesData2(:,2),conHesnz,2,2);
Hes = objHes+conHes;
Hes = (Hes+Hes.')/2;